// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAil0u-AIU06kCZ74gH_INb_OzkYo-_mSk',
    appId: '1:395826173283:web:b31d522b7c94a06e492f56',
    messagingSenderId: '395826173283',
    projectId: 'renton-cd593',
    authDomain: 'renton-cd593.firebaseapp.com',
    storageBucket: 'renton-cd593.firebasestorage.app',
    measurementId: 'G-R9HE2DS9Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM98hGaaGbXn4-wgTmZgc_SsI0CQy4Qmg',
    appId: '1:395826173283:android:8037bb9b69dde86f492f56',
    messagingSenderId: '395826173283',
    projectId: 'renton-cd593',
    storageBucket: 'renton-cd593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL-NnKeg5x3VS_6cId4IfMYE03cjUjquU',
    appId: '1:395826173283:ios:d17c3d3c677f688c492f56',
    messagingSenderId: '395826173283',
    projectId: 'renton-cd593',
    storageBucket: 'renton-cd593.firebasestorage.app',
    iosBundleId: 'com.example.rentOn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL-NnKeg5x3VS_6cId4IfMYE03cjUjquU',
    appId: '1:395826173283:ios:d17c3d3c677f688c492f56',
    messagingSenderId: '395826173283',
    projectId: 'renton-cd593',
    storageBucket: 'renton-cd593.firebasestorage.app',
    iosBundleId: 'com.example.rentOn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAil0u-AIU06kCZ74gH_INb_OzkYo-_mSk',
    appId: '1:395826173283:web:dc64d94a71d0b27e492f56',
    messagingSenderId: '395826173283',
    projectId: 'renton-cd593',
    authDomain: 'renton-cd593.firebaseapp.com',
    storageBucket: 'renton-cd593.firebasestorage.app',
    measurementId: 'G-SYN89HTEBS',
  );

}